FROM openjdk:17-jdk-alpine
LABEL maintainer="zsanzharko@github"

WORKDIR /

ARG BUILD_PATH
ARG PROJECT_NAME
ARG VERSION


ENV SPRING_PORT $SPRING_PORT
ENV DATASOURCE_URL $DATASOURCE_URL
ENV DATASOURCE_USERNAME $DATASOURCE_USERNAME
ENV DATASOURCE_PASSWORD $DATASOURCE_PASSWORD
ENV JPA_HIBERNATE_DDL_AUTO $JPA_HIBERNATE_DDL_AUTO
ENV MINIO_HOST $MINIO_HOST
ENV MINIO_BUCKET $MINIO_BUCKET
ENV MINIO_ACCESS_KEY $MINIO_ACCESS_KEY
ENV MINIO_SECRET_KEY $MINIO_SECRET_KEY

COPY $BUILD_PATH/$PROJECT_NAME-$VERSION.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"]